name: tale
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.3
  - xgboost
  - cython
  - dropbox
  - flask
  - nltk
  - numba
  - pandas
  - plotly
  - requests
  - scikit-learn
  - scipy
  - spacy
  - tqdm
  - cmake
  - hdbscan
  - matplotlib
  - networkx
  - shap
  - umap-learn
  - pip:
    - psutil
    - lime
    - scrapely
    - dcor
    - multicoretsne
    - skope-rules
    - tables
    - pattern3

